Develop
AlexeyKriva/rides-microservice pull request #1
Opened 2024-09-23 16:37 UTC by AlexeyKriva

2024-09-23 17:53 UTC, psidarovich requested changes

2024-09-23 17:53 UTC, psidarovich commented on src/main/java/com/software/modsen/ridesmicroservice/entities/ride/RideDto.java
> +    private Currency currency;
minor: please, use empty lines between params with lots of annotations. Hard to read

2024-09-23 17:53 UTC, psidarovich commented on src/main/java/com/software/modsen/ridesmicroservice/entities/ride/RidePutDto.java
> +    @NotNull(message = "Currency cannot be null.")
Minor: you can omit such messages, spring validation will make them for you

2024-09-23 17:53 UTC, psidarovich commented on src/main/java/com/software/modsen/ridesmicroservice/services/RideService.java
> +    private PassengerClient passengerClient;
Bad practice to use field injection. How will you test this class (unit tests)?

2024-09-23 17:53 UTC, psidarovich commented on src/main/java/com/software/modsen/ridesmicroservice/services/RideService.java
> +                )
Please, use filtration on db layer, not in memory

2024-09-24 11:26 UTC, AlexeyKriva commented on src/main/java/com/software/modsen/ridesmicroservice/services/RideService.java
> +                )
I updated this query to repository query with JPQL

2024-09-24 11:26 UTC, AlexeyKriva commented on src/main/java/com/software/modsen/ridesmicroservice/services/RideService.java
> +    private PassengerClient passengerClient;
I will fix these rows when i refactor files in my projects

2024-09-24 16:03 UTC, psidarovich approved these changes

2024-09-24 19:07 UTC, merged